name: github-actions
run-name: ${{ github.actor}} is learning Github Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node JS Environment
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Bats (A third party package)
        run: npm install -g bats

      - name: Run Test using bat package
        run: bats -v